const EVENTS_KEY = "agendaEvents";
const ALARM_PREFIX = "agenda-event-";

async function getEvents(){ const r=await chrome.storage.local.get(EVENTS_KEY); return r[EVENTS_KEY]||[]; }
function localDateISO(d){ return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
function addRecurrence(date,rec){ const d=new Date(date); if(rec==="daily")d.setDate(d.getDate()+1); if(rec==="weekly")d.setDate(d.getDate()+7); if(rec==="monthly")d.setMonth(d.getMonth()+1); return d; }
function occurrenceDates(event,start,end,max=200){ const first=new Date(`${event.date}T${event.time||"00:00"}`); if(!event.recurrence||event.recurrence==="none") return first>=start&&first<=end?[first]:[]; const until=event.repeatUntil?new Date(`${event.repeatUntil}T23:59:59`):end; const hard=until<end?until:end; const out=[]; let cur=new Date(first), guard=0; while(cur<=hard&&guard++<max){ if(cur>=start)out.push(new Date(cur)); cur=addRecurrence(cur,event.recurrence); } return out; }
async function rebuildAllReminders(){ const alarms=await chrome.alarms.getAll(); await Promise.all(alarms.filter(a=>a.name.startsWith(ALARM_PREFIX)).map(a=>chrome.alarms.clear(a.name))); const now=new Date(), horizon=new Date(Date.now()+1000*60*60*24*120); for(const e of await getEvents()){ const mins=Number(e.reminderMinutes??-1); if(mins<0)continue; for(const occ of occurrenceDates(e,new Date(now.getTime()-mins*60000),horizon)){ const when=occ.getTime()-mins*60000; if(when<=Date.now())continue; const occurrenceDate=localDateISO(occ); await chrome.alarms.create(`${ALARM_PREFIX}${e.id}-${occurrenceDate}`,{when}); } } }
chrome.runtime.onInstalled.addListener(rebuildAllReminders); chrome.runtime.onStartup.addListener(rebuildAllReminders); chrome.storage.onChanged.addListener((c,a)=>{if(a==="local"&&c[EVENTS_KEY])rebuildAllReminders();});
chrome.alarms.onAlarm.addListener(async alarm=>{ if(!alarm.name.startsWith(ALARM_PREFIX))return; const raw=alarm.name.slice(ALARM_PREFIX.length), match=raw.match(/^(.*)-(\d{4}-\d{2}-\d{2})$/); if(!match)return; const [,id,date]=match, event=(await getEvents()).find(e=>e.id===id); if(!event)return; await chrome.notifications.create(`notification-${id}-${date}`,{type:"basic",iconUrl:"icons/icon128.png",title:event.title||"Compromisso",message:`${date.split("-").reverse().join("/")} às ${event.time}${event.category?` • ${event.category}`:""}`,priority:2}); });
